### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by Steven4294** [dharness/angular2-scroll-glue#3]
./node_modules/angular2-scroll-glue/node_modules/reflect-metadata/Reflect.js
Module not found: Error: Can't resolve 'crypto' in '/Users/sp223c/Desktop/doorbell-web/node_modules/angular2-scroll-glue/node_modules/reflect-metadata'

**Comment by dharness** [comment]
Thanks! I am no longer maintaining this repo. I will update the readme
